### ISSUE TITLE
Cannot find this node in custom nodes manager.

### ISSUE THREAD

**Issue by MrUSBEN** [comfyanonymous/ComfyUI_bitsandbytes_NF4#14]
I updated comfy and searched for this node, but nothing comes up either related to bits or nf4.

**Comment by bejaranoo** [comment]
> I updated comfy and searched for this node, but nothing comes up either related to bits or nf4.

same

**Comment by awestbro** [comment]
I ran into the same issue, it seems like it was published to the [dev channel](https://github.com/ltdrdata/ComfyUI-Manager/commit/49a7db074dd5e992ae72b6405b13b9ee6534cdb0#diff-3e217803d10844a7213652b0e8a1ffe1df8933b7576e848344765b776edf3ec4
)

When you open the manager interface on the left side, you can select Channel: dev and see it in the list.

**Comment by MrUSBEN** [comment]
> I ran into the same issue, it seems like it was published to the [dev channel](https://github.com/ltdrdata/ComfyUI-Manager/commit/49a7db074dd5e992ae72b6405b13b9ee6534cdb0#diff-3e217803d10844a7213652b0e8a1ffe1df8933b7576e848344765b776edf3ec4)
> 
> When you open the manager interface on the left side, you can select Channel: dev and see it in the list.

That worked, thankyou.
