### ISSUE TITLE
I just get clone it and had this error

### ISSUE THREAD

**Issue by Sup-Shero** [comfyanonymous/ComfyUI_bitsandbytes_NF4#8]
i git clone it
and install python.exe -s -m pip install -U bitsandbytes
and I had this error
0.0 seconds (IMPORT FAILED): F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
how to fix it please I'm a noob

**Comment by Sup-Shero** [comment]
now, I tried after the update and installed bitsandbytes>=0.43.0 too with the same error I'm afraid 😨

**Comment by boricuapab** [comment]
Check this out, it should help you fix it.

https://www.youtube.com/watch?v=NkKyu181d_U

**Comment by Sup-Shero** [comment]
I did all of that but in cmd but i said why not let's try it and it is work !!!!!!
i liked the video and subscribed to you as thanks for the solution
thanks bro
